name: ToDoList Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3
          sudo apt install python3-pip
      - name: Run unit tests
        run: |
          python -m unittest todo_list_test.py
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-reports

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade setuptools wheel
          pip install --upgrade pip
          pip install build
      - name: Build package
        run: python setup.py sdist bdist_wheel

  notification:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Send email notification
        env:
          EMAIL_RECIPIENT: carl.betsa@ges.inatel.br
        run: |
          chmod +x scripts/shell.sh